package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"io/fs"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const marker = "generate:reset"

func main() {
	root := flag.String("root", ".", "корневая директория для сканирования пакетов")
	flag.Parse()

	dirs, filesByDir, err := collectPackageDirs(*root)
	if err != nil {
		log.Fatalf("сканирование директорий: %v", err)
	}

	total := 0
	for _, dir := range dirs {
		n, err := processPackage(dir, filesByDir[dir])
		if err != nil {
			log.Fatalf("обработка пакета %q: %v", dir, err)
		}
		total += n
	}

	log.Printf("готово: обработано пакетов с аннотированными структурами: %d", total)
}

// collectPackageDirs обходит дерево директорий от root и возвращает
// отсортированный список директорий, содержащих исходные .go-файлы
func collectPackageDirs(root string) ([]string, map[string][]string, error) {
	filesByDir := map[string][]string{}

	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if d.IsDir() {
			name := d.Name()
			if name != "." && name != root && shouldSkipDir(name) {
				return filepath.SkipDir
			}
			return nil
		}

		if !strings.HasSuffix(path, ".go") {
			return nil
		}
		base := filepath.Base(path)
		if strings.HasSuffix(base, "_test.go") || base == "reset.gen.go" {
			return nil
		}

		dir := filepath.Dir(path)
		filesByDir[dir] = append(filesByDir[dir], path)
		return nil
	})
	if err != nil {
		return nil, nil, err
	}

	dirs := make([]string, 0, len(filesByDir))
	for dir := range filesByDir {
		dirs = append(dirs, dir)
	}
	sort.Strings(dirs)

	return dirs, filesByDir, nil
}

func shouldSkipDir(name string) bool {
	if strings.HasPrefix(name, ".") || strings.HasPrefix(name, "_") {
		return true
	}
	switch name {
	case "vendor", "testdata", "node_modules":
		return true
	}
	return false
}

// annotatedStruct — структура, помеченная комментарием generate:reset
type annotatedStruct struct {
	name string
	st   *ast.StructType
}

// processPackage разбирает все исходные файлы одной директории (пакета),
// находит аннотированные структуры и, если такие есть, генерирует
// reset.gen.go. Возвращает количество сгенерированных структур.
func processPackage(dir string, files []string) (int, error) {
	if len(files) == 0 {
		return 0, nil
	}

	fset := token.NewFileSet()
	var astFiles []*ast.File
	pkgName := ""

	for _, f := range files {
		file, err := parser.ParseFile(fset, f, nil, parser.ParseComments)
		if err != nil {
			return 0, fmt.Errorf("parse %s: %w", f, err)
		}
		if pkgName == "" {
			pkgName = file.Name.Name
		} else if file.Name.Name != pkgName {
			log.Printf("пропуск %s: разные имена пакетов (%s и %s)", dir, pkgName, file.Name.Name)
			return 0, nil
		}
		astFiles = append(astFiles, file)
	}
	if pkgName == "" {
		return 0, nil
	}

	types := collectTypeDecls(astFiles)

	var annotated []annotatedStruct
	annotatedSet := map[string]bool{}

	for _, file := range astFiles {
		for _, decl := range file.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}
			for _, spec := range gd.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					continue
				}
				if !isAnnotated(gd, ts) {
					continue
				}
				annotatedSet[ts.Name.Name] = true
				annotated = append(annotated, annotatedStruct{name: ts.Name.Name, st: st})
			}
		}
	}

	genFile := filepath.Join(dir, "reset.gen.go")

	if len(annotated) == 0 {
		if _, err := os.Stat(genFile); err == nil {
			if err := os.Remove(genFile); err != nil {
				return 0, fmt.Errorf("удаление устаревшего %s: %w", genFile, err)
			}
		}
		return 0, nil
	}

	sort.Slice(annotated, func(i, j int) bool { return annotated[i].name < annotated[j].name })

	var b strings.Builder
	b.WriteString("// Code generated by cmd/reset; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkgName)

	for _, as := range annotated {
		b.WriteString(generateReset(fset, as.name, as.st, types, annotatedSet))
	}

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return 0, fmt.Errorf("форматирование сгенерированного кода для %s: %w", dir, err)
	}

	if err := os.WriteFile(genFile, formatted, 0644); err != nil {
		return 0, fmt.Errorf("запись %s: %w", genFile, err)
	}

	log.Printf("сгенерирован %s (%d структур)", genFile, len(annotated))
	return len(annotated), nil
}

// isAnnotated сообщает, помечена ли структура комментарием generate:reset.
// Комментарий может быть присоединён либо к самому TypeSpec
func isAnnotated(gd *ast.GenDecl, ts *ast.TypeSpec) bool {
	doc := ts.Doc
	if doc == nil && len(gd.Specs) == 1 {
		doc = gd.Doc
	}
	if doc == nil {
		return false
	}
	return strings.Contains(doc.Text(), marker)
}

// collectTypeDecls собирает карту "имя типа -> выражение его объявления"
// по всем файлам пакета. Используется для резолвинга полей с именованными
// типами (алиасами) до их фактического вида (примитив, слайс, мапа и т.д.).
func collectTypeDecls(files []*ast.File) map[string]ast.Expr {
	types := map[string]ast.Expr{}
	for _, file := range files {
		for _, decl := range file.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}
			for _, spec := range gd.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				types[ts.Name.Name] = ts.Type
			}
		}
	}
	return types
}

// typeKind классифицирует поле структуры для целей генерации кода сброса.
type typeKind int

const (
	kindUnknown typeKind = iota
	kindZero             // примитив: числовой тип, string, bool — сбрасывается к литералу zeroLit
	kindNilable          // interface/chan/func/error/any — сбрасывается в nil
	kindSlice
	kindMap
	kindArray  // массив фиксированного размера — сбрасывается к составному литералу arrayLit{}
	kindStruct // именованная структура, аннотированная generate:reset — имеет метод Reset()
	kindPointer
)

// kindInfo — результат резолвинга типа поля.
type kindInfo struct {
	kind     typeKind
	zeroLit  string    // для kindZero
	arrayLit string    // для kindArray: текст типа массива, напр. "[3]int"
	elem     *kindInfo // для kindPointer: род типа, на который указывает поле
}

// resolveType определяет typeKind для выражения типа поля expr, разворачивая
// именованные алиасы через types и проверяя принадлежность к annotated —
// множеству структур текущего пакета, для которых также генерируется Reset().
func resolveType(fset *token.FileSet, expr ast.Expr, types map[string]ast.Expr, annotated map[string]bool, depth int) kindInfo {
	if depth > 30 {
		return kindInfo{kind: kindUnknown}
	}

	switch t := expr.(type) {
	case *ast.Ident:
		switch t.Name {
		case "bool":
			return kindInfo{kind: kindZero, zeroLit: "false"}
		case "string":
			return kindInfo{kind: kindZero, zeroLit: `""`}
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
			"byte", "rune", "float32", "float64", "complex64", "complex128":
			return kindInfo{kind: kindZero, zeroLit: "0"}
		case "error", "any":
			return kindInfo{kind: kindNilable}
		}
		if annotated[t.Name] {
			return kindInfo{kind: kindStruct}
		}
		if underlying, ok := types[t.Name]; ok {
			return resolveType(fset, underlying, types, annotated, depth+1)
		}
		return kindInfo{kind: kindUnknown}

	case *ast.StarExpr:
		elem := resolveType(fset, t.X, types, annotated, depth+1)
		return kindInfo{kind: kindPointer, elem: &elem}

	case *ast.ArrayType:
		if t.Len == nil {
			return kindInfo{kind: kindSlice}
		}
		return kindInfo{kind: kindArray, arrayLit: exprString(fset, t)}

	case *ast.MapType:
		return kindInfo{kind: kindMap}

	case *ast.InterfaceType, *ast.ChanType, *ast.FuncType:
		return kindInfo{kind: kindNilable}

	default:
		return kindInfo{kind: kindUnknown}
	}
}

// exprString рендерит AST-выражение типа обратно в исходный текст Go
func exprString(fset *token.FileSet, expr ast.Expr) string {
	var buf bytes.Buffer
	if err := printer.Fprint(&buf, fset, expr); err != nil {
		return ""
	}
	return buf.String()
}

// generateReset генерирует исходный текст метода Reset() для структуры name.
func generateReset(fset *token.FileSet, name string, st *ast.StructType, types map[string]ast.Expr, annotated map[string]bool) string {
	var b strings.Builder

	fmt.Fprintf(&b, "func (rs *%s) Reset() {\n", name)
	b.WriteString("\tif rs == nil {\n\t\treturn\n\t}\n\n")

	for _, field := range st.Fields.List {
		names := field.Names
		if len(names) == 0 {
			// Анонимное (встроенное) поле — имя выводится из имени типа.
			embName := embeddedName(field.Type)
			if embName == "" || embName == "_" {
				continue
			}
			names = []*ast.Ident{ast.NewIdent(embName)}
		}

		ki := resolveType(fset, field.Type, types, annotated, 0)

		for _, n := range names {
			if n.Name == "_" {
				continue
			}
			target := "rs." + n.Name
			for _, line := range emitReset(target, ki) {
				b.WriteString("\t" + line + "\n")
			}
		}
	}

	b.WriteString("}\n\n")
	return b.String()
}

// embeddedName извлекает имя типа для анонимного (встроенного) поля,
// разворачивая возможный указатель и квалификацию пакетом.
func embeddedName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		return t.Sel.Name
	case *ast.StarExpr:
		return embeddedName(t.X)
	}
	return ""
}

// emitReset рекурсивно строит строки кода сброса значения, на которое
func emitReset(target string, ki kindInfo) []string {
	switch ki.kind {
	case kindZero:
		return []string{fmt.Sprintf("%s = %s", target, ki.zeroLit)}

	case kindNilable:
		return []string{fmt.Sprintf("%s = nil", target)}

	case kindSlice:
		return []string{fmt.Sprintf("%s = %s[:0]", target, target)}

	case kindMap:
		return []string{fmt.Sprintf("clear(%s)", target)}

	case kindArray:
		return []string{fmt.Sprintf("%s = %s{}", target, ki.arrayLit)}

	case kindStruct:
		return []string{fmt.Sprintf("%s.Reset()", target)}

	case kindPointer:
		// Указатель на аннотированную структуру: метод Reset() уже определён
		// с приёмником ровно такого же типа (*T), разыменование не нужно —
		// вызываем напрямую после проверки на nil.
		if ki.elem.kind == kindStruct {
			return []string{
				fmt.Sprintf("if %s != nil {", target),
				fmt.Sprintf("\t%s.Reset()", target),
				"}",
			}
		}

		inner := "*" + target
		body := emitReset(inner, *ki.elem)
		lines := make([]string, 0, len(body)+2)
		lines = append(lines, fmt.Sprintf("if %s != nil {", target))
		for _, l := range body {
			lines = append(lines, "\t"+l)
		}
		lines = append(lines, "}")
		return lines

	default: // kindUnknown
		return []string{fmt.Sprintf("// %s: неподдерживаемый тип поля, пропущено", target)}
	}
}
